import "./globals.css";
import Providers from "@/redux/providers";

export const metadata = {
  title: "Santa Ana",
  description: "Generated by create next app",
};

export default function RootLayout({ children}) {
  return (
    <html lang="es">
    <head>
        <link rel="icon" href="/img/icons8-cane.png" />
    </head>
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
