import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/redux/providers";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children, text }) {
  console.log(text)
  return (
    <html lang="es">
      <Providers>
        <body className={`${text}`}>{children}</body>
      </Providers>
    </html>
  );
}
